projectname         = "azureresume"
environment         = "dev"
location            = "West Europe"
location_short_code = "weeu"
appversion          = "0.1"
db_container        = "count"
db_name             = "visitorcounter2"
func_source         = "../counterapi/counterapi.zip"